import '../../models/activity_session.dart';

final List<ActivitySession> mockSessions = [
  ActivitySession(
    id: 'session_01',
    title: 'Library Study Session',
    activityType: 'Study',
    location: 'Central Library Floor 3',
    startTime: DateTime(DateTime.now().year, DateTime.now().month, DateTime.now().day, 14, 0),
    durationMinutes: 120,
    interactionLevel: 'Silent',
    minPartnerRating: 4.5,
    createdBy: 'user_02',
    status: 'open',
    notes: 'Quiet study session, bring your own materials',
  ),
  ActivitySession(
    id: 'session_02',
    title: 'Gym Workout Buddy',
    activityType: 'Fitness',
    location: 'Varsity Wellness Center',
    startTime: DateTime(DateTime.now().year, DateTime.now().month, DateTime.now().day, 16, 30),
    durationMinutes: 60,
    interactionLevel: 'Social',
    minPartnerRating: 4.0,
    createdBy: 'user_03',
    status: 'open',
    notes: 'Cardio and light weights session',
  ),
  ActivitySession(
    id: 'session_03',
    title: 'Code Review & Coffee',
    activityType: 'Study',
    location: 'Student Union Café',
    startTime: DateTime(DateTime.now().year, DateTime.now().month, DateTime.now().day, 11, 0),
    durationMinutes: 90,
    interactionLevel: 'Colab',
    minPartnerRating: 4.2,
    createdBy: 'user_02',
    status: 'open',
    notes: 'Reviewing Flutter projects together',
  ),
  ActivitySession(
    id: 'session_04',
    title: 'History Thesis Prep',
    activityType: 'Study',
    location: 'Arts Building B4',
    startTime: DateTime(DateTime.now().year, DateTime.now().month, DateTime.now().day, 15, 15),
    durationMinutes: 180,
    interactionLevel: 'Silent',
    minPartnerRating: 4.8,
    createdBy: 'user_03',
    status: 'open',
    notes: 'Working on thesis outlines silently',
  ),
  ActivitySession(
    id: 'session_05',
    title: 'Pick-up Basketball',
    activityType: 'Sports',
    location: 'University Gym Court 2',
    startTime: DateTime(DateTime.now().year, DateTime.now().month, DateTime.now().day, 17, 30),
    durationMinutes: 120,
    interactionLevel: 'Social',
    minPartnerRating: 4.3,
    createdBy: 'user_01',
    status: 'open',
    notes: '3v3 half court, bring water and a white or dark shirt',
  ),
  ActivitySession(
    id: 'session_06',
    title: 'Morning Walk at Oval',
    activityType: 'Walking',
    location: 'University Oval Track',
    startTime: DateTime(DateTime.now().year, DateTime.now().month, DateTime.now().day + 1, 6, 0),
    durationMinutes: 45,
    interactionLevel: 'Silent',
    minPartnerRating: 3.5,
    createdBy: 'user_01',
    status: 'open',
    notes: 'Casual morning walk, no talking needed',
  ),
];
