// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKSsE0sjzy7oniW3JE5OYfus5voc_eXl4',
    appId: '1:868778657512:web:0c0039ed1b7fc6f0d62b5d',
    messagingSenderId: '868778657512',
    projectId: 'swapspace-add2d',
    authDomain: 'swapspace-add2d.firebaseapp.com',
    storageBucket: 'swapspace-add2d.firebasestorage.app',
    measurementId: 'G-SYY9R95H09',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGn6LvLgH8mnn1PQp7lKAl2xWvroekvJk',
    appId: '1:868778657512:android:d6b31b68cb619640d62b5d',
    messagingSenderId: '868778657512',
    projectId: 'swapspace-add2d',
    storageBucket: 'swapspace-add2d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbtiHXc2uPMel2T4b1NmJKpp_ZswQMT2M',
    appId: '1:868778657512:ios:7338f0ae25771892d62b5d',
    messagingSenderId: '868778657512',
    projectId: 'swapspace-add2d',
    storageBucket: 'swapspace-add2d.firebasestorage.app',
    iosBundleId: 'com.example.swapspace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbtiHXc2uPMel2T4b1NmJKpp_ZswQMT2M',
    appId: '1:868778657512:ios:7338f0ae25771892d62b5d',
    messagingSenderId: '868778657512',
    projectId: 'swapspace-add2d',
    storageBucket: 'swapspace-add2d.firebasestorage.app',
    iosBundleId: 'com.example.swapspace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKSsE0sjzy7oniW3JE5OYfus5voc_eXl4',
    appId: '1:868778657512:web:b84204c64f8e9946d62b5d',
    messagingSenderId: '868778657512',
    projectId: 'swapspace-add2d',
    authDomain: 'swapspace-add2d.firebaseapp.com',
    storageBucket: 'swapspace-add2d.firebasestorage.app',
    measurementId: 'G-T1TG8Z3LBH',
  );
}
