// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: _requiredWithFallback('FIREBASE_WEB_API_KEY', 'AIzaSyBKSsE0sjzy7oniW3JE5OYfus5voc_eXl4'),
    appId: _requiredWithFallback('FIREBASE_WEB_APP_ID', '1:868778657512:web:0c0039ed1b7fc6f0d62b5d'),
    messagingSenderId: _requiredWithFallback('FIREBASE_WEB_MESSAGING_SENDER_ID', '868778657512'),
    projectId: _requiredWithFallback('FIREBASE_WEB_PROJECT_ID', 'swapspace-add2d'),
    authDomain: _optionalWithFallback('FIREBASE_WEB_AUTH_DOMAIN', 'swapspace-add2d.firebaseapp.com'),
    storageBucket: _optionalWithFallback('FIREBASE_WEB_STORAGE_BUCKET', 'swapspace-add2d.firebasestorage.app'),
    measurementId: _optionalWithFallback('FIREBASE_WEB_MEASUREMENT_ID', 'G-SYY9R95H09'),
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: _requiredWithFallback('FIREBASE_ANDROID_API_KEY', 'AIzaSyDGn6LvLgH8mnn1PQp7lKAl2xWvroekvJk'),
    appId: _requiredWithFallback('FIREBASE_ANDROID_APP_ID', '1:868778657512:android:d6b31b68cb619640d62b5d'),
    messagingSenderId: _requiredWithFallback('FIREBASE_ANDROID_MESSAGING_SENDER_ID', '868778657512'),
    projectId: _requiredWithFallback('FIREBASE_ANDROID_PROJECT_ID', 'swapspace-add2d'),
    storageBucket: _optionalWithFallback('FIREBASE_ANDROID_STORAGE_BUCKET', 'swapspace-add2d.firebasestorage.app'),
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: _requiredWithFallback('FIREBASE_IOS_API_KEY', 'AIzaSyBbtiHXc2uPMel2T4b1NmJKpp_ZswQMT2M'),
    appId: _requiredWithFallback('FIREBASE_IOS_APP_ID', '1:868778657512:ios:7338f0ae25771892d62b5d'),
    messagingSenderId: _requiredWithFallback('FIREBASE_IOS_MESSAGING_SENDER_ID', '868778657512'),
    projectId: _requiredWithFallback('FIREBASE_IOS_PROJECT_ID', 'swapspace-add2d'),
    storageBucket: _optionalWithFallback('FIREBASE_IOS_STORAGE_BUCKET', 'swapspace-add2d.firebasestorage.app'),
    iosBundleId: _optionalWithFallback('FIREBASE_IOS_BUNDLE_ID', 'com.example.swapspace'),
  );

  static FirebaseOptions get macos => FirebaseOptions(
    apiKey: _requiredWithFallback('FIREBASE_MACOS_API_KEY', 'AIzaSyBbtiHXc2uPMel2T4b1NmJKpp_ZswQMT2M'),
    appId: _requiredWithFallback('FIREBASE_MACOS_APP_ID', '1:868778657512:ios:7338f0ae25771892d62b5d'),
    messagingSenderId: _requiredWithFallback('FIREBASE_MACOS_MESSAGING_SENDER_ID', '868778657512'),
    projectId: _requiredWithFallback('FIREBASE_MACOS_PROJECT_ID', 'swapspace-add2d'),
    storageBucket: _optionalWithFallback('FIREBASE_MACOS_STORAGE_BUCKET', 'swapspace-add2d.firebasestorage.app'),
    iosBundleId: _optionalWithFallback('FIREBASE_MACOS_BUNDLE_ID', 'com.example.swapspace'),
  );

  static FirebaseOptions get windows => FirebaseOptions(
    apiKey: _requiredWithFallback('FIREBASE_WINDOWS_API_KEY', 'AIzaSyBKSsE0sjzy7oniW3JE5OYfus5voc_eXl4'),
    appId: _requiredWithFallback('FIREBASE_WINDOWS_APP_ID', '1:868778657512:web:b84204c64f8e9946d62b5d'),
    messagingSenderId: _requiredWithFallback('FIREBASE_WINDOWS_MESSAGING_SENDER_ID', '868778657512'),
    projectId: _requiredWithFallback('FIREBASE_WINDOWS_PROJECT_ID', 'swapspace-add2d'),
    authDomain: _optionalWithFallback('FIREBASE_WINDOWS_AUTH_DOMAIN', 'swapspace-add2d.firebaseapp.com'),
    storageBucket: _optionalWithFallback('FIREBASE_WINDOWS_STORAGE_BUCKET', 'swapspace-add2d.firebasestorage.app'),
    measurementId: _optionalWithFallback('FIREBASE_WINDOWS_MEASUREMENT_ID', 'G-T1TG8Z3LBH'),
  );

  static String _requiredWithFallback(String key, String fallback) {
    final value = dotenv.env[key]?.trim();
    final isPlaceholder = value != null && value.startsWith('your-');
    if (value == null || value.isEmpty || isPlaceholder) {
      return fallback;
    }

    return value;
  }

  static String? _optionalWithFallback(String key, String? fallback) {
    final value = dotenv.env[key]?.trim();
    if (value == null || value.isEmpty) {
      return fallback;
    }

    return value;
  }
}
